config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users, :controllers => { registrations: 'users/registrations' }

  root :to => "pages#home"
  resources :quizzes do
    member do
      get :show_results
    end
  end

  get '/about' => 'pages#about'

put 'admins/:id', to: 'admins#select_quiz', as: :select_quiz

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :quiz_questions do
    resources :quiz_answers, only: :create
    member do
      get :show_question
      get :show_answers
      get :show_correct_answer
    end
  end
  resources :admins

  resources :questions

  resources :answers

  resources :rounds do
    member do
      get :show_round_results
    end
  end
  mount ActionCable.server => "/cable"
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :set_quiz, only: [:show, :edit, :update, :destroy, :show_results]

 # def new
 #    @quiz = Quiz.new
 #    authorize @quiz
 #  end

  def create
    @quiz = Quiz.new(quiz_params)
    @quiz_admin_id = current_admin.id
    @quiz.admin_id = @quiz_admin_id
    set_quiz_pin
    @quiz.pin_number = @random_pin_number
    # authorize @quiz
    if @quiz.save
      redirect_to edit_quiz_path(@quiz)
    else
      render :new
    end
  end

  def show
    @first_round = @rounds.first
  end

  def show_results
    @users_ranked = User.where(quiz_id: @quiz.id).order(total_score: :desc, total_time: :desc)
    @speedster = User.where(quiz_id: @quiz.id).order(total_time: :desc).first
    @slowster = User.where(quiz_id: @quiz.id).order(total_time: :desc).last
    @loser = User.where(quiz_id: @quiz.id).order(total_score: :desc).last
    @language = @quiz.language
    broadcast_total_results
    @quiz.users.each do |user|
      sign_out user
      user.destroy
    end
    @quiz.users.destroy_all
  end

  def edit
    @new_round = Round.new
    @new_question = Question.new
  end

  # def edit
  #     authorize @quiz
  # end

  def update
  #   authorize @quiz
    if @quiz.update(quiz_params)
      redirect_to edit_quiz_path(@quiz)
    else
    render :edit
    end
  end

  # def destroy
  #   authorize @quiz
  #   @quiz.destroy
  #   redirect_to new_quiz_path
  # end

private

  def quiz_params
    params.require(:quiz).permit(:name, :language, :timer, :time_bonus)
  end

  def set_quiz_pin
    @random_pin_number = rand(1..10) + 10*rand(1..10) + 100*rand(1..10) + 1000*rand(1..10)
    until Quiz.where(pin_number: @random_pin_number).empty? do
      @random_pin_number = rand(1..10) + 10*rand(1..10) + 100*rand(1..10) + 1000*rand(1..10)
    end
  end

  def set_quiz
    @quiz = Quiz.find(params[:id])
    @rounds = Round.where(quiz_id: @quiz.id)
    @quiz_questions = []
    @rounds.each do |round|
      @quiz_questions << QuizQuestion.where(round_id: round.id)
    end
  end

  def broadcast_total_results
    ActionCable.server.broadcast("quiz_room_#{@quiz.id}", {
      admin_partial: ApplicationController.renderer.render(
        partial: "quizzes/admin_results",
        locals: {users_ranked: @users_ranked, language: @language, speedster: @speedster, slowster: @slowster, loser: @loser}),
        # current_admin: current_admin
    })

    @quiz.users.each do |user|
        ActionCable.server.broadcast("player_quiz_room_#{user.id}", {
          event: "player_results",
          player_partial: ApplicationController.renderer.render(
            partial: "quizzes/player_results",
            locals: {users_ranked: @users_ranked, player_ranking: @users_ranked.index(user), user_points: user.total_score, language: @language}),
          # current_user_id: current_user.id,
        })
    end
  end

end

app/views/quizzes/_admin_results.html.erb
<div class="hidden-xs hidden-sm">

  <% if language == "english" %>

    <div class="title">Top scorers!</div>

    <div class="podium">

      <% unless users_ranked[1].nil? %>
        <div class="podium-right podium-item">
          <%= image_tag "second-place.png" %>
          <div class="results-description">
            <div class="results">
              <p class="name"><%= users_ranked[1].name%></p>
              <p class="points"><%= users_ranked[1].total_score%> pts</p>
              <%= image_tag "#{users_ranked[1].avatar}.png", class: "avatar-podium" %>
            </div>
          </div>
        </div>
      <% end %>

      <% unless users_ranked[0].nil? %>
        <div class="podium-top podium-item">
          <%= image_tag "first-place.png" %>
          <div class="results-description">
            <div class="results">
              <p class="name"><%= users_ranked[0].name%></p>
              <p class="points"><%= users_ranked[0].total_score%> pts</p>
              <%= image_tag "#{users_ranked[0].avatar}.png", class: "avatar-podium" %>
            </div>
          </div>
        </div>
      <% end %>

      <% unless users_ranked[2].nil? %>
        <div class="podium-left podium-item">
          <%= image_tag "third-place.png" %>
          <div class="results-description">
            <div class="results">
              <p class="name"><%= users_ranked[2].name%></p>
              <p class="points"><%= users_ranked[2].total_score%> pts</p>
            </div>
            <div class="avatar-results">
              <%= image_tag "#{users_ranked[2].avatar}.png", class: "avatar-podium" %>
            </div>
          </div>
        </div>
      <% end %>

    </div>

  <% else %>

    <div class="title">Meilleurs scores!</div>

    <div class="podium">

      <% unless users_ranked[1].nil? %>
        <div class="podium-right podium-item">
          <%= image_tag "second-place.png" %>
          <div class="results-description">
            <div class="results">
              <p class="name"><%= users_ranked[1].name%></p>
              <p class="points"><%= users_ranked[1].total_score%> pts</p>
              <%= image_tag "#{users_ranked[1].avatar}.png", class: "avatar-podium" %>
            </div>
          </div>
        </div>
      <% end %>

      <% unless users_ranked[0].nil? %>
        <div class="podium-top podium-item">
          <%= image_tag "first-place.png" %>
          <div class="results-description">
            <div class="results">
              <p class="name"><%= users_ranked[0].name%></p>
              <p class="points"><%= users_ranked[0].total_score%> pts</p>
              <%= image_tag "#{users_ranked[0].avatar}.png", class: "avatar-podium" %>
            </div>
          </div>
        </div>
      <% end %>

      <% unless users_ranked[2].nil? %>
        <div class="podium-left podium-item">
          <%= image_tag "third-place.png" %>
          <div class="results-description">
            <div class="results">
              <p class="name"><%= users_ranked[2].name%></p>
              <p class="points"><%= users_ranked[2].total_score%> pts</p>
            </div>
            <div class="avatar-results">
              <%= image_tag "#{users_ranked[2].avatar}.png", class: "avatar-podium" %>
            </div>
          </div>
        </div>
      <% end %>

    </div>

  <% end %>

</div>


<div class="hidden-md hidden-lg">
  <div class="container text-center">
    <div class="row">
      <div class="col-xs-12">
        <div class="question-displayed"><p>Speedster: <%=  speedster.name %></p></div>
      </div>
      <div class="col-xs-12">
        <div class="question-displayed"><p>Slowster: <%=  slowster.name %></p></div>
      </div>
      <div class="col-xs-12">
        <div class="question-displayed"><p>Loser: <%=  loser.name %></p></div>
      </div>
      <div class="col-xs-12">
        <div class="btn btn-control-next" id="next"><%= link_to "finish game", root_path %></div>
      </div>
    </div>
  </div>
</div>

app/views/quizzes/_new_player.html.erb
<div class="question-displayed"><%=user_name%></div>

app/views/quizzes/_player_results.html.erb
<% if language == "english" %>

  <div class="wrapper">
    <div class="text-centered-results">
      <div class="text-centered-results-vertical">
        <div class="congrats">
          Thank you for playing !
        </div>

        <div class="textresults">
          You ranked
          <%= player_ranking + 1 %> out of
            <%= users_ranked.length %> with
              <%= user_points %> points
        </div>

      </div>
    </div>
  </div>

<% else %>

  <div class="wrapper">
    <div class="text-centered-results">
      <div class="text-centered-results-vertical">
        <div class="congrats">
          Merci d'avoir joué !
        </div>

        <div class="textresults">
          Tu as fini
          <%= player_ranking + 1 %> sur
            <%= users_ranked.length %> avec
              <%= user_points %> points
        </div>

      </div>
    </div>
  </div>

<% end %>

app/views/quizzes/_results.html.erb
<div class="container text-center">
  <h3><%= "Results" %></h3>
</div>

app/views/quizzes/edit.html.erb
<div class="hidden-md hidden-lg">
  <div class="container-central-information">
    <i class="fas fa-tablet"> <i class="fas fa-undo"></i> or </i><i class="fas fa-desktop"></i>
    <p>Connect on a larger screen (tablet or computer) to edit quiz</p>
  </div>
</div>
<div class="hidden-xs hidden-sm">
  <div class="wrapper-quiz-details">
    <div class="quiz-details-container">
      <%= simple_form_for @quiz do |f| %>
       <div class="container">
            <div class="col-md-6 col-sm-3">
              <div class="quiz-detail-container">
                <div class="quiz-detail-title">
                  Quiz name
                </div>
                <div class="quiz-detail">
                  <%= f.input :name, placeholder: @quiz.name, label: false %>
                </div>
              </div>
            </div>
            <div class="col-md-6 col-sm-3">
              <div class="quiz-detail-container">
                <div class="quiz-detail-title">
                  Pin number
                </div>
                <div class="quiz-detail">
                  <%= f.input :pin_number, placeholder: @quiz.pin_number, disabled: true, label: false %>
                </div>
              </div>
            </div>
            <div class="col-md-6 col-sm-3">
              <div class="quiz-detail-container">
                <div class="quiz-detail-title">
                  Language
                </div>
                <div class="quiz-detail">
                  <%= f.input :language, as: :radio_buttons, collection: [['french', 'French'], ['english', 'English']], label_method: :second, value_method: :first, label: false %>
                </div>
              </div>
            </div>
            <div class="col-md-6 col-sm-3">
              <div class="quiz-detail-container">
                <div class="quiz-detail-title">
                  Timer
                </div>
                <div class="quiz-detail">
                  <%= f.input :timer, as: :radio_buttons, collection: [[true, 'Yes'], [false, 'No']], label_method: :second, value_method: :first, label: false %>
                </div>
              </div>
            </div>
            <div class="col-md-6 col-sm-3">
              <div class="quiz-detail-container">
                <div class="quiz-detail-title">
                  Time bonus
                </div>
                <div class="quiz-detail">
                  <%= f.input :time_bonus, as: :radio_buttons, collection: [[true, 'Yes'], [false, 'No']], label_method: :second, value_method: :first, label: false %>
                </div>
              </div>
            </div>
            <div class="col-md-6 col-sm-3">
              <div class="quiz-detail-container">
                <%= f.submit' Save quiz parameters', class: 'quiz-detail-save' %>
  <!--                 <div class="quiz-detail-title">
                  </div> -->
              </div>
            </div>
          </div>
      <% end %>
    </div>
  </div>
  <div class="wrapper-rounds-edit">
    <div class="container-rounds-edit">
      <% @quiz.rounds.each do |round| %>
        <div id="round<%=round.id%>">
          <%= render 'quizzes/edit_partials/round_details_edit', round: round %>
        </div>
        <div class="container-round-edit-questions collapse" id="round-questions<%=round.id%>">
          <% round.quiz_questions.each do |quiz_question| %>
            <%question = Question.find(quiz_question.question_id)%>
            <div id="question<%=question.id%>" class="question-selector">
              <%= render 'quizzes/edit_partials/question_details_edit', question: question %>
            </div>
            <div class="container-round-edit-question-answers collapse" id="question-answers<%=question.id%>">
              <% question.answers.each do |answer| %>
                <div id="answer<%=answer.id%>">
                  <%= render 'quizzes/edit_partials/answer_details_edit', answer: answer %>
                </div>
              <% end %>
            </div>
          <% end %>
          <div class="container-new-question">
            <div class="btn new-question-modal-button" data-toggle="modal" data-target="#newQuestionModal<%=round.id%>" data-id="<%=round.id%>">
              <i class="fas fa-plus-circle"></i>Add new question
            </div>
            <%= render 'quizzes/edit_partials/new_question_modal', round: round %>
          </div>
        </div>
      <% end %>
      <div class="container-new-round">
        <div class="btn new-round" data-toggle="modal" data-target="#newRoundModal">
          <i class="fas fa-plus-circle"></i>Add new round
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade" id="newRoundModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-new-round" role="document">
      <div class="modal-new-round-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle"></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close" >
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <%= simple_form_for(@new_round, remote: true) do |f| %>
          <div class="modal-body">
            <%= f.association :category %>
            <%= f.input :no_of_questions %>
            <%= f.input :quiz_id, as: :hidden, input_html: {value: f.object.quiz_id || params[:id]} %>
          </div>
          <div class="modal-footer">
            <%= f.submit class: 'quiz-detail-save' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>




<% content_for :after_js do %>
  <script>

    const showRoundEditForm = () => {
      const rounds = document.getElementsByClassName('round-selector');
      const roundEditButtons = document.getElementsByClassName('round-edit-details-edit-button')
      const showRoundForm = () => {
        console.log(event.currentTarget.parentElement);
        console.log(event.currentTarget.parentElement.nextElementSibling);
        var roundPresentationDiv = event.currentTarget.parentElement;
        var roundEditForm = roundPresentationDiv.nextElementSibling;
        roundEditForm.classList.remove("hidden");
        roundPresentationDiv.classList.add("hidden");
      }
      for (var i = 0; i< roundEditButtons.length; i++) {
        roundEditButtons[i].addEventListener("click", showRoundForm);
      }
    }

    const cancelRoundEdit = () => {
      const cancelRoundEditButtons = document.getElementsByClassName('round-edit-details-form-cancel');
      const hideRoundForm = () => {
        console.log(event.currentTarget.parentElement.parentElement.parentElement);
        console.log(event.currentTarget.parentElement.parentElement.parentElement.previousElementSibling);
        var roundEditForm = event.currentTarget.parentElement.parentElement.parentElement;
        var roundPresentationDiv = roundEditForm.previousElementSibling;
        roundEditForm.classList.add("hidden");
        roundPresentationDiv.classList.remove("hidden");
      }

      for (var i = 0; i< cancelRoundEditButtons.length; i++) {
        cancelRoundEditButtons[i].addEventListener("click", hideRoundForm);
      }
    }

    const showQuestionEditForm = () => {
      const questions = document.getElementsByClassName('question-selector');
      const questionEditButtons = document.getElementsByClassName('round-edit-question-details-edit-button')
      const showQuestionForm = () => {
        console.log(event.currentTarget.parentElement);
        console.log(event.currentTarget.parentElement.nextElementSibling);
        var questionPresentationDiv = event.currentTarget.parentElement;
        var questionEditForm = questionPresentationDiv.nextElementSibling;
        questionEditForm.classList.remove("hidden");
        questionPresentationDiv.classList.add("hidden");
      }
      for (var i = 0; i< questionEditButtons.length; i++) {
        questionEditButtons[i].addEventListener("click", showQuestionForm);
      }
    }

    const cancelQuestionEdit = () => {
      const cancelQuestionEditButtons = document.getElementsByClassName('round-edit-question-details-form-cancel');
      const hideQuestionForm = () => {
        console.log(event.currentTarget.parentElement.parentElement.parentElement);
        console.log(event.currentTarget.parentElement.parentElement.parentElement.previousElementSibling);
        var questionEditForm = event.currentTarget.parentElement.parentElement.parentElement;
        var questionPresentationDiv = questionEditForm.previousElementSibling;
        questionEditForm.classList.add("hidden");
        questionPresentationDiv.classList.remove("hidden");
      }

      for (var i = 0; i< cancelQuestionEditButtons.length; i++) {
        cancelQuestionEditButtons[i].addEventListener("click", hideQuestionForm);
      }
    }

    const showAnswerEditForm = () => {
      const answers = document.getElementsByClassName('answer-selector');
      const answerEditButtons = document.getElementsByClassName('round-edit-question-answer-details-edit-button')
      const showAnswerForm = () => {
        console.log(event.currentTarget.parentElement);
        console.log(event.currentTarget.parentElement.nextElementSibling);
        var answerEditForm = event.currentTarget.parentElement.nextElementSibling;
        var answerPresentationDiv = event.currentTarget.parentElement;
        answerEditForm.classList.remove("hidden");
        answerPresentationDiv.classList.add("hidden");
      }
      for (var i = 0; i< answerEditButtons.length; i++) {
        answerEditButtons[i].addEventListener("click", showAnswerForm);
      }
    }

    const cancelAnswerEdit = () => {
      const cancelAnswerEditButtons = document.getElementsByClassName('round-edit-question-answer-details-form-cancel');
      const hideAnswerForm = () => {
        console.log(event.currentTarget.parentElement.parentElement.parentElement);
        console.log(event.currentTarget.parentElement.parentElement.parentElement.previousElementSibling);
        var questionEditForm = event.currentTarget.parentElement.parentElement.parentElement;
        var questionPresentationDiv = event.currentTarget.parentElement.parentElement.parentElement.previousElementSibling;
        questionEditForm.classList.add("hidden");
        questionPresentationDiv.classList.remove("hidden");
      }

      for (var i = 0; i< cancelAnswerEditButtons.length; i++) {
        cancelAnswerEditButtons[i].addEventListener("click", hideAnswerForm);
      }
    }

    const closeNewRoundModal = () => {
      const newRoundModal = document.getElementById('newRoundModal');
      const newRoundModalForms = newRoundModal.getElementsByClassName('simple_form');
      if (newRoundModalForms.length == 0) {
        location.reload()
      } else {
        if (window.confirm("You haven't properly saved all of the new questions. Are you sure you want to exit?")) {
          location.reload()}
      }
    }

    const closeNewQuestionModal = () => {
      const newQuestionModal = document.getElementsByClassName('OpenedModal').first;
      const newQuestionForm = newQuestionModal.getElementsByClassName('simple_form');
      if (newQuestionForm.length == 0) {
        location.reload()
      } else {
        if (window.confirm("You haven't saved the new question. Are you sure you want to exit?")) {
          location.reload()}
      }
    }

    const openNewQuestionModal = () => {
      const newQuestionButtons = document.getElementsByClassName('new-question-modal-button');
      const passOpenedIdToQuestionModal = () => {
        console.log(event.currentTarget);
        var newQuestionModalPressedButton = event.currentTarget;
        console.log(newQuestionModalPressedButton);
        var newQuestionModalId = String(newQuestionModalPressedButton.getAttribute("data-target"));
        var newQuestionModalIdTrimmed = newQuestionModalId.substring(1)
        console.log(newQuestionModalIdTrimmed);
        var newQuestionModal = document.getElementById(newQuestionModalIdTrimmed);
        console.log(newQuestionModal);
        newQuestionModal.classList.add('openedNewQuestionModal');

      }
      for (var i = 0; i< newQuestionButtons.length; i++) {
        newQuestionButtons[i].addEventListener("click", passOpenedIdToQuestionModal);
      }
    }

    showRoundEditForm();

    cancelRoundEdit();

    showQuestionEditForm();

    cancelQuestionEdit();

    showAnswerEditForm();

    cancelAnswerEdit();

    openNewQuestionModal();

  </script>
<% end %>

app/views/quizzes/show.html.erb
<% if @quiz.rounds.empty? %>
  <div class="container-central-information">
    <p>This quiz is empty</p>
    <% if current_admin == @quiz.admin %>
      <%= link_to "Edit quiz", edit_quiz_path(@quiz), class: 'button-central-information' %>
    <% end %>
  </div>
<% else %>
  <div id="avatar">
    <% unless current_admin == @quiz.admin %>
    <div class="hidden-md hidden-lg">
      <div class="avatar-container">
        <div class="avatar-badge">
          <%= image_tag "#{current_user.avatar}.png" %>
        </div>
      </div>
    </div>
    <% end %>
  </div>

  <% if @language == "english" %>

    <div id="quiz" data-admin="<%= current_user == @quiz.user %>">
      <% if current_admin == @quiz.admin %>
        <div class="hidden-xs hidden-sm">
          <div class="container text-center welcome">
            <div class="main" id="access-info">
              <div class="secondary-child">
                <i class="fa fa-hand-o-right" aria-hidden="true"></i>
                <h1>www.ninjaquiz.ninja</h1>
              </div>
              <div class="secondary-child">
                <i class="fa fa-th" aria-hidden="true"></i>
                <h1>Game PIN: <%= @quiz.pin_number %></h1>
              </div>
            </div>
            <div class="row" id="new_team">
            </div>
          </div>
        </div>
        <div class="hidden-md hidden-lg">
          <div class="container text-center">
            <div class="row">
              <div class="col-xs-12">
                <% if @quiz.rounds.length == 1 %>
                  <div class="btn btn-control-next" id="next"><%= link_to "First question", quiz_question_path(@first_round.quiz_questions.first), remote: true %></div>
                <% else %>
                  <div class="btn btn-control-next" id="next"><%= link_to "First round", round_path(@first_round), remote: true %></div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% else %>
        <div class="container text-center">
          <h1>Get ready ninjas!</h1>
        </div>
      <% end %>
    </div>

  <% else %>

    <div id="quiz" data-admin="<%= current_admin == @quiz.admin %>">
      <% if current_admin == @quiz.admin %>
        <div class="hidden-xs hidden-sm">
          <div class="container text-center welcome">
            <div class="main" id="access-info">
              <div class="secondary-child">
                <i class="fa fa-hand-o-right" aria-hidden="true"></i>
                <h1>www.ninjaquiz.ninja</h1>
              </div>
              <div class="secondary-child">
                <i class="fa fa-th" aria-hidden="true"></i>
                <h1>Code de la partie: <%= @quiz.pin_number %></h1>
              </div>
            </div>
            <div class="row" id="new_team">
            </div>
          </div>
        </div>
        <div class="hidden-md hidden-lg">
          <div class="container text-center">
            <div class="row">
              <div class="col-xs-12">
                <% if @quiz.rounds.length == 1 %>
                  <div class="btn btn-control-next" id="next"><%= link_to "First question", quiz_question_path(@first_round.quiz_questions.first), remote: true %></div>
                <% else %>
                  <div class="btn btn-control-next" id="next"><%= link_to "First round", round_path(@first_round), remote: true %></div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% else %>
        <div class="container text-center">
          <h1>Preparez-vous les ninjas!</h1>
        </div>
      <% end %>
    </div>

  <% end %>


  <% if current_user %>

    <% content_for :after_js do %>
      <script>

        const onAnswerSelect = () => {
          const answers = document.getElementsByClassName("ninja-input");

          const answerSelect = () => {
            for (var i = 0; i< answers.length; i++) {
              answers[i].classList.add("unselected_answer", "disabled_item");
              event.currentTarget.classList.remove("unselected_answer");
              event.currentTarget.classList.add("selected_answer");
            }

            event.currentTarget.classList.add("selected_answer");
          };

          for (var i = 0; i< answers.length; i++) {
            answers[i].addEventListener("click", answerSelect);
          }
        }

        App['quiz_room_<%= @quiz.id %>'] = App.cable.subscriptions.create(
          { channel: 'QuizRoomChannel', quiz_room_id: <%= @quiz.id %> },
          { received: (data) => {
            console.log("event");
            quiz = document.getElementById("quiz");
            if (quiz.dataset.admin == "true") {
              if (data.event == "new_team") {
                const access = document.getElementById("access-info");
                if (access.classList.contains("main")) {
                  access.classList.remove("main");
                  access.classList.add("secondary");
                }
                new_team = document.getElementById("new_team");
                new_team.innerHTML = data.admin_partial;
              }
              else {
                quiz.innerHTML = data.admin_partial;
              }
            }
            else if (data.player_partial){
              quiz.innerHTML = data.player_partial;
              document.getElementById("avatar").innerHTML = "";
            }
            }
          });

        App['player_quiz_room_<%= current_user.id %>'] = App.cable.subscriptions.create(
          { channel: 'PlayerQuizRoomChannel', player_id: <%= current_user.id %> },
          { received: (data) => {
            console.log("event player");
            quiz = document.getElementById("quiz");
            if (quiz.dataset.admin == "false") {
              if (data.event == "question_answer") {
                quiz.innerHTML = data.player_partial;
                if (data.timer === true) {
                  var avatarCountdown = document.getElementById("avatar-countdown");
                  if (avatarCountdown) {
                    var countdownId = avatarCountdown.dataset.countdownId;
                    clearTimeout(countdownId);
                  }
                  document.getElementById("avatar").innerHTML = "";
                }
                if (data.timer === false) {
                  document.getElementById("avatar").innerHTML = "";
                }
              }
              else if (data.event == "player_results") {
                quiz.innerHTML = data.player_partial;
              }
              else if (data.event == "answer_display_player") {
                if (data.timer === true) {
                  document.getElementById("avatar").innerHTML = data.player_partial_avatar_countdown;
                  quiz.innerHTML = data.player_partial;
                  var avatarCountdown = document.getElementById("avatar-countdown");
                  var countdownId = setTimeout(function() {
                  if (avatarCountdown) {
                    avatarCountdown.innerHTML = data.player_partial_avatar_still;
                    quiz.innerHTML = data.player_partial_time_up;
                  }
                  }, 12000);
                  avatarCountdown.dataset.countdownId = countdownId;
                }
                if (data.timer === false) {
                  document.getElementById("avatar").innerHTML = data.player_partial_avatar_still;
                }
                onAnswerSelect();
              }
            }
          }});
      </script>
    <% end %>
  <% else %>

    <% content_for :after_js do %>
      <script>

        const onAnswerSelect = () => {
          const answers = document.getElementsByClassName("ninja-input");

          const answerSelect = () => {
            for (var i = 0; i< answers.length; i++) {
              answers[i].classList.add("unselected_answer", "disabled_item");
              event.currentTarget.classList.remove("unselected_answer");
              event.currentTarget.classList.add("selected_answer");
            }

            event.currentTarget.classList.add("selected_answer");
          };

          for (var i = 0; i< answers.length; i++) {
            answers[i].addEventListener("click", answerSelect);
          }
        }

        App['quiz_room_<%= @quiz.id %>'] = App.cable.subscriptions.create(
          { channel: 'QuizRoomChannel', quiz_room_id: <%= @quiz.id %> },
          { received: (data) => {
            console.log("event");
            quiz = document.getElementById("quiz");
            if (quiz.dataset.admin == "true") {
              if (data.event == "new_team") {
                const access = document.getElementById("access-info");
                if (access.classList.contains("main")) {
                  access.classList.remove("main");
                  access.classList.add("secondary");
                }
                new_team = document.getElementById("new_team");
                new_team.innerHTML = data.admin_partial;
              }
              else {
                quiz.innerHTML = data.admin_partial;
              }
            }
            else if (data.player_partial){
              quiz.innerHTML = data.player_partial;
              document.getElementById("avatar").innerHTML = "";
            }
            }
          });

      </script>
    <% end %>

  <% end %>
<% end %>