config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users, :controllers => { registrations: 'users/registrations' }

  root :to => "pages#home"
  resources :quizzes do
    member do
      get :show_results
    end
  end

  get '/about' => 'pages#about'

put 'admins/:id', to: 'admins#select_quiz', as: :select_quiz

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :quiz_questions do
    resources :quiz_answers, only: :create
    member do
      get :show_question
      get :show_answers
      get :show_correct_answer
    end
  end
  resources :admins

  resources :questions

  resources :answers

  resources :rounds do
    member do
      get :show_round_results
    end
  end
  mount ActionCable.server => "/cable"
end

app/views/admins/_quizzes_selection.html.erb
<% admin_quizzes.each do |quiz| %>
  <%= link_to select_quiz_path(current_admin.id, selected_quiz_id: quiz.id), method: :put, remote: true do %>
    <% if selected_quiz_id == quiz.id %>
      <div class="quiz-choice selected-quiz" value="<%=quiz.id%>"">
        <div class="quiz-choice-name">
          <%= quiz.name %>
        </div>
        <div class="quiz-choice-created-at">
          created <%= quiz.created_at.strftime("%d-%m-%Y") %>
        </div>
      </div>
    <% else %>
      <div class="quiz-choice" value="<%=quiz.id%>"">
        <div class="quiz-choice-name">
          <%= quiz.name %>
        </div>
        <div class="quiz-choice-created-at">
          created <%= quiz.created_at.strftime("%d-%m-%Y") %>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/admins/_selected_quiz_buttons.html.erb
<div id="launch-quiz-button">
  <%= link_to quiz_path(selected_quiz_id) do%>
    <div class="admin-home-actions">Launch quiz</div>
  <% end %>
</div>
<div id="edit-quiz-button">
  <%= link_to edit_quiz_path(selected_quiz_id) do%>
    <div class="admin-home-actions">Edit quiz</div>
  <% end %>
</div>
<div class="btn admin-home-actions btn-green" data-toggle="modal" data-target="#newQuizModal">New Quiz</div>

app/views/admins/select_quiz.js.erb
function refreshButtons(buttonsHTML) {
  const actionButtons = document.getElementById('quiz-action-buttons');
  actionButtons.innerHTML = buttonsHTML;
}

function refreshQuizzes(quizListHTML) {
  const quizzesContainer = document.getElementById('quiz-selection-container');
  quizzesContainer.innerHTML = quizListHTML;
}

refreshButtons('<%= j render "admins/selected_quiz_buttons", selected_quiz_id: @selected_quiz.id %>');
refreshQuizzes('<%= j render "admins/quizzes_selection", selected_quiz_id: @selected_quiz.id, admin_quizzes: current_admin.quizzes %>');

app/views/admins/show.html.erb
<% if @admin_quizzes.empty? %>

  <div class="container-central-information">
    <p>You have no quizzes yet</p>
    <div class="btn btn-green button-central-information" data-toggle="modal" data-target="#newQuizModal">New Quiz</div>
  </div>

<% else %>

  <div class="wrapper-launch">
    <div class="container-launch">
      <%= link_to quiz_path(@admin_quizzes.last) do %>
        <div class="admin-home-actions-quick-play">Quick launch quiz "<%=@selected_quiz.name%>"</div>
      <% end %>
    </div>
  </div>
  <div class="wrapper-quiz-choice-actions">
    <div class="wrapper-quiz-choice">
      <div class="container-quizzes-choice-header">
        <h3>My quizzes</h3>
  <!--       <div class="quiz-choice-name-header">
          <h3>Quiz name</h3>
        </div>
        <div class="quiz-choice-created-at-header">
          <h3>Created on</h3>
        </div> -->
      </div>
      <div class="container-quizzes-choice" id="quiz-selection-container">
        <%= render 'admins/quizzes_selection', admin_quizzes: @admin_quizzes, selected_quiz_id: @selected_quiz.id %>
      </div>
    </div>
    <div class="container-quizzes-actions" id="quiz-action-buttons">
      <%= render 'admins/selected_quiz_buttons', selected_quiz_id: @selected_quiz.id %>
    </div>
  </div>

<% end %>

<div class="modal fade" id="newQuizModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-new-quiz" role="document">
      <div class="modal-new-quiz-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle"></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close" >
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <%= simple_form_for(@new_quiz) do |f| %>
          <div class="container container-new-quiz">
            <div class="row">
              <div class="col-md-6 col-sm-3">
                <div class="quiz-detail-container">
                  <div class="quiz-detail-title">
                    Quiz name
                  </div>
                  <div class="quiz-detail">
                    <%= f.input :name, placeholder: "enter name", label: false %>
                  </div>
                </div>
              </div>
              <div class="col-md-6 col-sm-3">
                <div class="quiz-detail-container">
                  <div class="quiz-detail-title">
                    Language
                  </div>
                  <div class="quiz-detail">
                    <%= f.input :language, as: :radio_buttons, collection: [['french', 'French'], ['english', 'English']], label_method: :second, value_method: :first, label: false %>
                  </div>
                </div>
              </div>
              <div class="col-md-6 col-sm-3">
                <div class="quiz-detail-container">
                  <div class="quiz-detail-title">
                    Timer
                  </div>
                  <div class="quiz-detail">
                    <%= f.input :timer, as: :radio_buttons, collection: [[true, 'Yes'], [false, 'No']], label_method: :second, value_method: :first, label: false %>
                  </div>
                </div>
              </div>
              <div class="col-md-6 col-sm-3">
                <div class="quiz-detail-container">
                  <div class="quiz-detail-title">
                    Time bonus
                  </div>
                  <div class="quiz-detail">
                    <%= f.input :time_bonus, as: :radio_buttons, collection: [[true, 'Yes'], [false, 'No']], label_method: :second, value_method: :first, label: false %>
                  </div>
                </div>
              </div>
              <div class="col-md-6 col-sm-3">
                <div class="quiz-detail-container">
                  <%= f.submit' Save quiz', class: 'quiz-detail-save' %>
    <!--                 <div class="quiz-detail-title">
                    </div> -->
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

<% content_for :after_js do %>
  <script>

    // const onQuizSelect = () => {
    //   const quizzes = document.getElementsByClassName("quiz-choice");
    //   const launchButton = document.getElementById("launch-quiz-button");
    //   const editButton = document.getElementById("edit-quiz-button");
    //   console.log(quizzes)

    //   const quizSelect = () => {
    //     const previousQuizId = document.getElementsByClassName("selected-quiz").first.getAttribute('value');
    //     for (var i=0; i < quizzes.length; i++) {
    //       quizzes[i].classList.remove("selected-quiz");
    //     }
    //     event.currentTarget.classList.add("selected-quiz");
    //     const selectedQuizId = event.currentTarget.getAttribute('value');
    //     launchButton.innerHTML = ("<a href='/quizzes/show/${selectedQuizId}' a>");
    //     editButton.innerHTML = ("<a href='/quizzes/edit/${selectedQuizId}' a>");
    //   }
    //   for (var i = 0; i< quizzes.length; i++) {
    //     quizzes[i].addEventListener("click", quizSelect);
    //   }
    // }

    // onQuizSelect();

  </script>
<% end %>