config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users, :controllers => { registrations: 'users/registrations' }

  root :to => "pages#home"
  resources :quizzes do
    member do
      get :show_results
    end
  end

  get '/about' => 'pages#about'

put 'admins/:id', to: 'admins#select_quiz', as: :select_quiz

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :quiz_questions do
    resources :quiz_answers, only: :create
    member do
      get :show_question
      get :show_answers
      get :show_correct_answer
    end
  end
  resources :admins

  resources :questions

  resources :answers

  resources :rounds do
    member do
      get :show_round_results
    end
  end
  mount ActionCable.server => "/cable"
end

app/models/quiz_question.rb
class QuizQuestion < ApplicationRecord
  belongs_to :question
  belongs_to :round
  has_many :quiz_answers, dependent: :destroy
end

app/controllers/quiz_questions_controller.rb
class QuizQuestionsController < ApplicationController
  before_action :set_quiz_question, :set_user, only: [:show, :show_question, :show_answers, :show_correct_answer]

  def show
    broadcast_before_question
  end

  def create
    @quiz_question = QuizQuestion.new(quiz_question_params)
    @quiz_question.position = quiz_question_params[:position]
    @round = @quiz_question.round
    @question = @quiz_question.question
    if @quiz_question.save
      respond_to do |format|
        format.html { redirect_to request.referer }
        format.js
      end
    else
      render :edit
    end
  end

  def show_question
    broadcast_show_question
  end

  def show_answers
    @quiz_answer = QuizAnswer.new
    @start = Time.now
    broadcast_show_answers
  end

  def show_correct_answer
    broadcast_show_correct_answer
  end

  def show_wait_room
    broadcast_wait_room
  end

  private

  def quiz_question_params
    params.require(:quiz_question).permit(:round_id, :question_id, :position)
  end

  def set_quiz_question
    @quiz_question = QuizQuestion.find(params[:id])
    unless @quiz_question == @quiz_question.round.quiz_questions.last
      @next_quiz_question = QuizQuestion.find(params[:id].to_i + 1)
    end
    @answers = @quiz_question.question.answers
    @quiz = @quiz_question.round.quiz
    @language = @quiz.language
    @timer = @quiz.timer
  end

  def set_user
    current_user == nil ? @current_user_id = nil : @current_user_id = current_user.id
  end

  def broadcast_before_question
      ActionCable.server.broadcast("quiz_room_#{@quiz_question.round.quiz_id}", {
        admin_partial: ApplicationController.renderer.render(
          partial: "quiz_questions/quiz_question_admin_before_question",
          locals: {quiz_question: @quiz_question, answers: @answers, next_quiz_question: @next_quiz_question, language: @language}),
        player_partial: ApplicationController.renderer.render(
          partial: "quiz_questions/quiz_question_player_before_question",
          locals: {language: @language}),
        current_admin_id: current_admin.id,
        })
  end

  def broadcast_show_question
      ActionCable.server.broadcast("quiz_room_#{@quiz_question.round.quiz_id}", {
        admin_partial: ApplicationController.renderer.render(
          partial: "quiz_questions/quiz_question_admin_before_answers",
          locals: {quiz_question: @quiz_question, answers: @answers, language: @language}),
        player_partial: ApplicationController.renderer.render(
          partial: "quiz_questions/quiz_question_player_before_answers",
          locals: {language: @language}),
        current_admin_id: current_admin.id, language: @language
        })
  end

  def broadcast_show_answers

    # broadcast view to admin allowing it to know how many players have answered
    ActionCable.server.broadcast("quiz_room_#{@quiz_question.round.quiz_id}", {
      admin_partial: ApplicationController.renderer.render(
        partial: "quiz_questions/quiz_question_admin_before_correct_answer",
        locals: {quiz_question: @quiz_question, answers: @answers, number_of_player_answers:0, language: @language}),
      # check if this partial is necessary
      player_partial: ApplicationController.renderer.render(
        partial: "quiz_questions/quiz_question_player_before_correct_answer",
        locals: {quiz_answer: @quiz_answer, quiz_question: @quiz_question, answers: @answers, start: @start, language: @language}),
      current_admin_id: current_admin.id,
    })

    if @quiz.timer == false

      @quiz.users.each do |user|
          ActionCable.server.broadcast("player_quiz_room_#{user.id}", {
            event: "answer_display_player",
            timer: false,
            player_partial: ApplicationController.renderer.render(
              partial: "quiz_questions/quiz_question_player_before_correct_answer",
              locals: {quiz_answer: @quiz_answer, quiz_question: @quiz_question, answers: @answers, start: @start, language: @language}),
            player_partial_avatar_still: ApplicationController.renderer.render(
              partial: "quiz_questions/quiz_question_player_avatar_still",
              locals: {user: user, language: @language}),
            current_admin_id: current_admin.id,
              })
      end

    else

      @quiz.users.each do |user|
          ActionCable.server.broadcast("player_quiz_room_#{user.id}", {
            event: "answer_display_player",
            timer: true,
            player_partial: ApplicationController.renderer.render(
              partial: "quiz_questions/quiz_question_player_before_correct_answer",
              locals: {quiz_answer: @quiz_answer, quiz_question: @quiz_question, answers: @answers, start: @start, language: @language}),
            player_partial_time_up: ApplicationController.renderer.render(
              partial: "quiz_questions/quiz_question_player_time_up"),
            player_partial_avatar_countdown: ApplicationController.renderer.render(
              partial: "quiz_questions/quiz_question_player_avatar_countdown",
              locals: {user: user, language: @language}),
            player_partial_avatar_still: ApplicationController.renderer.render(
              partial: "quiz_questions/quiz_question_player_avatar_still",
              locals: {user: user, language: @language}),
            current_admin_id: current_admin.id,
              })
      end
    end

  end

  def broadcast_show_correct_answer

    # broadcast view with correct answer to admin
    ActionCable.server.broadcast("quiz_room_#{@quiz_question.round.quiz_id}", {
      admin_partial: ApplicationController.renderer.render(
        partial: "quiz_questions/quiz_question_admin_after_correct_answer",
        locals: {quiz_question: @quiz_question, answers: @answers, next_quiz_question: @next_quiz_question, language: @language}),
      current_admin_id: current_admin.id,
        })

    # broacast to each user the view allowing them to know if they answered correctly or not
    @quiz.users.each do |user|
        ActionCable.server.broadcast("player_quiz_room_#{user.id}", {
          event: "question_answer",
          timer: @timer,
          player_partial: ApplicationController.renderer.render(
            partial: "quiz_questions/quiz_question_player_after_correct_answer",
            locals: {quiz_answer: QuizAnswer.where(quiz_question_id: @quiz_question.id, user_id: user.id).last, quiz_question: @quiz_question, user: user, language: @language}),
          current_admin_id: current_admin.id,
            })
    end
  end
end

app/views/quiz_questions/_quiz_question_admin_after_correct_answer.html.erb
<div class="hidden-xs hidden-sm">
  <div class="wrapper-display-admin">
    <div class="question-display-admin">
      <div><%=  raw quiz_question.question.content %></div>
    </div>
    <div class="answer-center-admin">
      <div class="answer-container-admin">
        <% answers.each do |answer| %>
          <% if answer.is_correct %>
            <div class="answer-hidden answer-display-admin correct-displayed">
              <%= answer.content %>
            </div>
          <% else %>
            <div class="answer-hidden answer-display-admin">
              <%= answer.content %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="hidden-md hidden-lg">
  <div class="container text-center">
    <div class="row">
      <div class="col-xs-12">
        <div class="question-display-admin-mobile"><p><%= raw quiz_question.question.content %></p></div>
      </div>
      <% answers.each do |answer| %>
          <div class="col-xs-12">
            <% if answer.is_correct %>
              <div class="answer-displayed-small-correct">
                <p><%=  answer.content %></p><br>
                <div class="players-who-answered-container">
                  <% QuizAnswer.where(quiz_question_id: quiz_question.id, answer_id: answer.id).limit(3).each do |quiz_answer| %>
                    <div class="player-who-answered-name">
                      <p> <%=quiz_answer.user.name%></p>
                    </div>
                  <% end %>
                </div>
              </div>
            <% else %>
              <div class="answer-displayed-small">
                <p><%=  answer.content %></p><br>
                <div class="players-who-answered-container">
                  <% QuizAnswer.where(quiz_question_id: quiz_question.id, answer_id: answer.id).limit(3).each do |quiz_answer| %>
                    <div class="player-who-answered-name">
                      <p> <%=quiz_answer.user.name%></p>
                    </div>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
      <% end %>
      <div class="col-xs-12">
        <% if quiz_question.round.quiz_questions.last == quiz_question %>
          <% if quiz_question.round.quiz.rounds.last == quiz_question.round %>
            <%= link_to "Finish game", show_results_quiz_path(quiz_question.round.quiz), remote: true, class: 'btn btn-control-next', id:'next' %>
          <% else %>
            <%= link_to "Finish round", show_round_results_round_path(quiz_question.round), remote: true, class: 'btn btn-control-next', id:'next' %>
          <% end %>
        <% else %>
          <%= link_to "Next Question", quiz_question_path(next_quiz_question), remote: true, class: 'btn btn-control-next', id:'next' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/quiz_questions/_quiz_question_admin_before_answers.html.erb
<div class="hidden-xs hidden-sm">
  <div class="wrapper-display-admin">
    <div class="question-full-display">
      <%=  raw quiz_question.question.content %>
    </div>
  </div>
</div>
<div class="hidden-md hidden-lg">
  <div class="container text-center">
    <div class="row">
      <div class="col-xs-12">
        <div class="question-display-admin-mobile"><p><%=  raw quiz_question.question.content %></p></div>
      </div>
      <% answers.each do |answer| %>
        <div class="col-xs-12">
          <div class="info-display-admin-mobile"><p><%=  answer.content %></p></div>
        </div>
      <% end %>
      <div class="col-xs-12">
        <%= link_to "Show answers", show_answers_quiz_question_path(quiz_question), remote: true, class: 'btn btn-control-next', id: 'show answers' %>
      </div>
      <div class="col-xs-12">
        <%= link_to "Back to question", show_question_quiz_question_path(quiz_question), remote: true, class: 'btn btn-control-back', id: 'show question' %>
      </div>
    </div>
  </div>
</div>

app/views/quiz_questions/_quiz_question_admin_before_correct_answer.html.erb
<div class="hidden-xs hidden-sm">
  <div class="wrapper-display-admin">
    <div class="question-display-admin">
      <div><%=  raw quiz_question.question.content %></div>
    </div>
    <div class="answer-center-admin">
      <div class="answer-container-admin">
      <% answers.each do |answer| %>
        <div class="answer-display-admin">
          <%= raw answer.content %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="hidden-md hidden-lg">
  <div class="container text-center">
    <div class="row">
      <div class="col-xs-12">
        <div class="question-display-admin-mobile"><p><%= raw quiz_question.question.content %></p></div>
      </div>
      <div class="col-xs-12">
        <div class="info-display-admin-mobile"><p>Answered by <%= number_of_player_answers %> players</p></div>
      </div>
      <div class="col-xs-12">
        <%= link_to "Show correct answer", show_correct_answer_quiz_question_path(quiz_question), remote: true, class: 'btn btn-control-next', id: 'correct answer' %></div>
      </div>
    </div>
  </div>
</div>

app/views/quiz_questions/_quiz_question_admin_before_question.html.erb
<div class="hidden-xs hidden-sm wrapper">
    <div class="container text-center" id="container-question">
      <div class="question-full-display">
        QUESTION
      </div>
    </div>
  </div>
  <div class="hidden-md hidden-lg">
    <div class="container text-center">
      <div class="row">
        <div class="col-xs-12">
          <div class="question-display-admin-mobile"><p><%= raw quiz_question.question.content %></p></div>
        </div>
        <div class="col-xs-12">
          <%= link_to "Show question", show_question_quiz_question_path(quiz_question), remote: true, class: 'btn btn-control-next', id:'show question' %></div>
        </div>
        <div class="col-xs-12">
          <% if quiz_question.round.quiz_questions.last == quiz_question %>
            <% if quiz_question.round.quiz.rounds.last == quiz_question.round %>
              <%= link_to "Finish game", show_results_quiz_path(quiz_question.round.quiz), remote: true, class: 'btn btn-control-next', id:'next' %>
              <% else %>
                <%= link_to "Finish round", show_round_results_round_path(quiz_question.round), remote: true, class: 'btn btn-control-next', id:'next' %>
              <% end %>
            <% else %>
              <%= link_to "Skip question", quiz_question_path(next_quiz_question), remote: true, class: 'btn btn-control-skip', id:'next' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/quiz_questions/_quiz_question_admin_wait_room.html.erb
<div class="col-sm-3">
  <div class="card-player mother" id="counter">
    <% if nb_players < 2 %>
      <h2><%= nb_players %> ninja playing!</h2>
    <% else %>
      <h2><%= nb_players %> ninjas playing!</h2>
    <% end %>
  </div>
</div>
<% quiz.users.reverse.each do |user| %>
  <% unless user.name == "Barman" %>
    <div class="col-sm-3">
      <div class="card-player mother">
        <div class="child">
          <h3><%= user.name %></h3>
        </div>
        <% if user.avatar == "" || user.avatar.nil? %>
          <div class="child">
            <% user.avatar = ["Ninja1", "Ninja2", "Ninja3", "Ninja4", "Ninja5", "Ninja6", "Ninja7", "Ninja8"].sample %>
            <% user.save %>
            <%= image_tag "#{user.avatar}.png", class: "avatar-big" %>
          </div>
        <% else %>
          <div class="child">
            <%= image_tag "#{user.avatar}.png", class: "avatar-big" %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/quiz_questions/_quiz_question_player_after_correct_answer.html.erb
<% if language == "english" %>

  <div class="hidden-md hidden-lg">
    <% if quiz_answer.nil? %>
      <div class="container-text-failure">
        <div class="svg text-center">
          <svg width="120" height="120" viewBox="-263.5 236.5 26 26">
            <g class="svg-failure">
              <circle cx="-250.5" cy="249.5" r="12"/>
              <path d="M-253 246l6 8-7.8"/>
              <path d="M-247 246l-6 8-7.8"/>
            </g>
          </svg>
           <div class="central-text"><h4>You did not answer.. </h4></div>
           <div class="central-text"><h4>Hurry up next time! </h4></div>
        </div>
      </div>
    <% else %>
      <% if quiz_answer.answer.is_correct %>
      <div class="container-text-success">
        <div class="svg text-center">
          <svg width="120" height="120" viewBox="-263.5 236.5 26 26">
            <g class="svg-success">
              <circle cx="-250.5" cy="249.5" r="12"/>
              <path d="M-256.46 249.65l3.9 3.74 8.02-7.8"/>
            </g>
          </svg>
          <div class="central-text"><h4><%= ["Correct!", "Amazing!", "Well done!", "Good job!"].sample %> You scored <%= quiz_answer.points%> points</h4></div>
        </div>
      </div>
      <% else %>
      <div class="container-text-failure">
        <div class="svg text-center">
          <svg width="120" height="120" viewBox="-263.5 236.5 26 26">
            <g class="svg-failure">
              <circle cx="-250.5" cy="249.5" r="12"/>
              <path d="M-253 246l6 8-7.8" />
              <path d="M-247 246l-6 8-7.8" />
            </g>
          </svg>
          <div class="central-text"><h4><%= ["Come on dude, focus!", "Not quite!", "Wrong!"].sample %></h4></div>
        </div>
        </div>
      <% end %>
    <% end %>
  </div>

<% else %>

  <div class="hidden-md hidden-lg">
    <% if quiz_answer.nil? %>
      <div class="container-text-failure">
        <div class="svg text-center">
          <svg width="120" height="120" viewBox="-263.5 236.5 26 26">
            <g class="svg-failure">
              <circle cx="-250.5" cy="249.5" r="12"/>
              <path d="M-253 246l6 8-7.8"/>
              <path d="M-247 246l-6 8-7.8"/>
            </g>
          </svg>
           <div class="central-text"><h4>Vous n'avez pas répondu.. </h4></div>
           <div class="central-text"><h4>Depeches-toi la prochaine fois! </h4></div>
        </div>
      </div>
    <% else %>
      <% if quiz_answer.answer.is_correct %>
      <div class="container-text-success">
        <div class="svg text-center">
          <svg width="120" height="120" viewBox="-263.5 236.5 26 26">
            <g class="svg-success">
              <circle cx="-250.5" cy="249.5" r="12"/>
              <path d="M-256.46 249.65l3.9 3.74 8.02-7.8"/>
            </g>
          </svg>
          <div class="central-text"><h4><%= ["Correct!", "Bien joué!", "Bravo!", "Tu es en feu!"].sample %> Tu marques <%= quiz_answer.points%> points</h4></div>
        </div>
      </div>
      <% else %>
      <div class="container-text-failure">
        <div class="svg text-center">
          <svg width="120" height="120" viewBox="-263.5 236.5 26 26">
            <g class="svg-failure">
              <circle cx="-250.5" cy="249.5" r="12"/>
              <path d="M-253 246l6 8-7.8" />
              <path d="M-247 246l-6 8-7.8" />
            </g>
          </svg>
          <div class="central-text"><h4><%= ["Allez concentre toi!", "Raté!", "Eh non!"].sample %></h4></div>
        </div>
        </div>
      <% end %>
    <% end %>
  </div>

<% end %>

app/views/quiz_questions/_quiz_question_player_avatar_countdown.html.erb
<div id="avatar-countdown">
  <div class="hidden-md hidden-lg">
    <div class="avatar-container">
      <div class="avatar-badge badge-countdown" id="countdown">
        <div id="avatar_countdown"><%= image_tag "#{user.avatar}.png" %></div>
        <div id="circle_countdown">
          <svg style=" position: absolute; top: 0; right: 0; width: 100%; height: 100%; transform: rotateY(-180deg) rotateZ(-90deg)">
            <circle r="46" cx="50" cy="50" style="stroke-dasharray: 290px; stroke-dashoffset: 0px; stroke-linecap: round; stroke-width: 4px; stroke: white; fill: none; animation: countdown 12s linear infinite forwards"></circle>
          </svg>
        </div>
      </div>
    </div>
</div>

app/views/quiz_questions/_quiz_question_player_avatar_still.html.erb
<div class="hidden-md hidden-lg">
  <div class="avatar-container" id="avatar">
    <div class="avatar-badge">
      <%= image_tag "#{user.avatar}.png" %>
    </div>
  </div>
</div>

app/views/quiz_questions/_quiz_question_player_before_answers.html.erb
<% if language == "english" %>

  <div class="hidden-md hidden-lg">
    <div class="container-text">
      <p class="central-text">Get ready to answer</p>
    </div>
  </div>

<% else %>

  <div class="hidden-md hidden-lg">
    <div class="container-text">
      <p class="central-text">Preparez vous a repondre</p>
    </div>
  </div>

<% end %>

app/views/quiz_questions/_quiz_question_player_before_correct_answer.html.erb
<div class="hidden-md hidden-lg">
  <div class="answer-container answer_form" id="flexanswer">
  <% answers.each do |answer| %>
    <%= simple_form_for([quiz_question, quiz_answer], remote: true) do |f| %>
      <input type="hidden" value="<%= answer.id %>" name="answer_id">
      <input type="hidden" value="<%= start %>" name="start">
      <%= f.submit "#{raw answer.content}", class: 'ninja-input' %>
    <% end %>
  <% end %>
  </div>
</div>

app/views/quiz_questions/_quiz_question_player_before_question.html.erb
<% if language == "english" %>

  <div class="hidden-md hidden-lg">
    <div class="container-text">
      <p class="central-text">Watch the screen</p>
    </div>
  </div>

<% else %>

  <div class="hidden-md hidden-lg">
    <div class="container-text">
      <p class="central-text">Regardez l'ecran principal</p>
    </div>
  </div>

<% end %>

app/views/quiz_questions/_quiz_question_player_time_up.html.erb
<% if language == "english" %>

  <div class="hidden-md hidden-lg">
    <div class="container-text">
      <p class="central-text">Time's up!</p>
    </div>
  </div>

<% else %>

  <div class="hidden-md hidden-lg">
    <div class="container-text">
      <p class="central-text">Temps écoulé</p>
    </div>
  </div>

<% end %>

app/views/quiz_questions/_quiz_question_player_wait_room.html.erb
<% if language == "english" %>

  <div class="hidden-md hidden-lg">
    <div class="container text-center">
      <h3>Waiting for other players</h3>
      <% if nb_players > 1 %>
        <p>Currently <%= nb_players %> ninjas connected</p>
      <% else %>
        <p>Currently <%= nb_players %> ninja connected</p>
      <% end %>
    </div>
  </div>

<% else %>

  <div class="hidden-md hidden-lg">
    <div class="container text-center">
      <h3>En attente d'autres joueurs</h3>
      <% if nb_players > 1 %>
        <p><%= nb_players %> ninjas connectés</p>
      <% else %>
        <p><%= nb_players %> ninja connecté</p>
      <% end %>
    </div>
  </div>

<% end %>

app/views/quiz_questions/create.js.erb
//APPLICABLE WHEN CREATING QUESTIONS WHILE CREATING A NEW ROUND - refresh the modal in order to replace the form and show the question as definitely validated

function refreshSavedQuestionForm(questionHTML, wrapperId) {
  const savedQuestionForm = document.getElementById(wrapperId);
  console.log(savedQuestionForm)
  savedQuestionForm.innerHTML = questionHTML;
}

// APPLICABLE WHEN CREATING NEW QUESTION - refresh the new question modal in order to keep adding new questions

function refreshNewQuestionModal(modalHTML, modalId) {
  const selectedModal = document.getElementById(modalId);
  console.log(selectedModal);
  selectedModal.getElementsByClassName('close')[0].click();
  selectedModal.outerHTML = modalHTML;
}

// APPLICABLE WHEN CREATING NEW QUESTION - add the new question to the list of questions for the round concerned

function appendQuestionToRound(questionHTML, answersContainerHTML, questionDiv, roundId, questionId) {
  const roundSelector = document.getElementById(roundId);
  console.log(roundSelector);
  const roundAnswers = roundSelector.getElementsByClassName('container-round-edit-question-answers');
  const roundLastAnswer = roundAnswers[roundAnswers.length - 1];
  console.log(roundLastAnswer);
  roundLastAnswer.insertAdjacentHTML('afterend', questionDiv);
  const questionSelector = document.getElementById(questionId);
  questionSelector.innerHTML = questionHTML;
  questionSelector.insertAdjacentHTML('afterend', answersContainerHTML);
}

// APPLICABLE WHEN CREATING NEW QUESTION - add the new question to the list of questions for the round concerned

function appendAnswerToQuestion(answerHTML, questionId) {
  const questionSelector = document.getElementById(questionId);
  console.log(questionSelector);
  questionSelector.insertAdjacentHTML('afterbegin', answerHTML);
}

// The difference position nil vs position defined allows to determine whether we are creating questions directly (one at a time) or while creating a round (could be several questions i.e. need a position to order them)

<% if @quiz_question.position == nil %>
  appendQuestionToRound('<%= j render "quizzes/edit_partials/question_details_edit", question: @question %>', '<div class="container-round-edit-question-answers collapse" id="question-answers<%=@question.id%>"></div>', '<div id="question<%=@question.id%>" class="question-selector"></div>', 'round-questions<%=@round.id%>', 'question<%=@question.id%>');
  refreshNewQuestionModal('<%= j render "quizzes/edit_partials/new_question_modal", round: @round %>', "newQuestionModal<%=@round.id%>");
  <% @quiz_question.question.answers.reverse.each do |answer| %>
    appendAnswerToQuestion('<%= j render "quizzes/edit_partials/answer_details_edit", answer: answer %>', "question-answers<%=@question.id%>");
  <% end %>
  showQuestionEditForm();
  cancelQuestionEdit();
  showAnswerEditForm();
  cancelAnswerEdit();
<% else %>
  refreshSavedQuestionForm('<%= j render "quizzes/edit_partials/newly_saved_question_new_round_modal", question_position: @quiz_question.position, question: @question %>', 'wrapper_new_question<%=@quiz_question.position%>');
<% end %>