config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users, :controllers => { registrations: 'users/registrations' }

  root :to => "pages#home"
  resources :quizzes do
    member do
      get :show_results
    end
  end

  get '/about' => 'pages#about'

put 'admins/:id', to: 'admins#select_quiz', as: :select_quiz

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :quiz_questions do
    resources :quiz_answers, only: :create
    member do
      get :show_question
      get :show_answers
      get :show_correct_answer
    end
  end
  resources :admins

  resources :questions

  resources :answers

  resources :rounds do
    member do
      get :show_round_results
    end
  end
  mount ActionCable.server => "/cable"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon hidden-xs hidden-sm">
  <!-- Logo -->
  <div class="navbar-left">
    <%= link_to root_path, class: "navbar-wagon-brand" do %>
      <%= image_tag "logo.svg", height: 45 %>
    <% end %>

    <%= link_to root_path, class: "navbar-wagon-item btn btn-navbar" do %>
      <%= "home"%>
    <% end %>
  </div>


  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if admin_signed_in? %>

      <!-- Links when logged in -->

      <!-- Avatar with dropdown menu -->

      <%= link_to admin_path(current_admin), class: "navbar-wagon-item btn btn-navbar" do %>
        <%= "my quizzes"%>
      <% end %>
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <div class="navbar-wagon-item btn btn-navbar" data-toggle="dropdown">
            <i class="fas fa-user"></i><%="logged in"%>
          </div>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
            </li>
            <li>
              <%= link_to edit_admin_registration_path(current_admin) do %>
                <i class="fas fa-users-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fas fa-sign-out-alt"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "log in"), new_admin_session_path, class: "navbar-wagon-item btn btn-navbar" %>
    <% end %>
  </div>
</div>
  <!-- Dropdown list appearing on mobile only -->
<div class="navbar-wagon hidden-md hidden-lg">
  <% if admin_signed_in? %>
    <div class="navbar-left">
      <%= link_to root_path, class: "navbar-wagon-brand" do %>
        <%= image_tag "logo.svg", height: 30 %>
      <% end %>
    </div>
    <div class="navbar-wagon-right"></div>
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "my quizzes", admin_path(current_admin)%></li>
          <li><%= link_to "Edit my profile", edit_admin_registration_path(current_admin)%></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete%></li>
        </ul>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_player_avatar.html.erb
<div class="avatar-container">
    <div class="avatar-badge">
      <%= image_tag "#{current_user.avatar}.png" %>
    </div>
</div>